name: datascience
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - pillow
  - pip
  - pip:
    - torch
    - torchvision
    - mlflow
    - boto3
    - python-dotenv
    - fastapi
    - uvicorn
    - kaggle
